source = ~/.config/hypr/model/palette.model.conf
source = ~/.config/hypr/controller/monitor.controller.conf
source = ~/.config/hypr/controller/input.controller.conf
source = ~/.config/hypr/controller/env.controller.conf
source = ~/.config/hypr/controller/bind.controller.conf
source = ~/.config/hypr/service/decoration.service.conf
source = ~/.config/hypr/service/animation.service.conf
source = ~/.config/hypr/service/layout.service.conf
source = ~/.config/hypr/controller/autostart.controller.conf

general {
    col.active_border = $mauve
    col.inactive_border = $surface0
    col.nogroup_border = $surface0
    col.resize = $surface2
}
