font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size 11.0

include model/palette.model.conf

cursor #f5e0dc
cursor_text_color #1e1e2e

window_padding_width 12
window_padding_height 12
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0
background_opacity 0.95
background_blur 6

map F11 toggle_fullscreen
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+up scroll_line_up
map ctrl+shift+down scroll_line_down

single_instance yes
allow_remote_control yes

cursor_shape block
enable_audio_bell no
